### ISSUE TITLE
Error on train.feature

### ISSUE THREAD

**Issue by miqbal23** [jvking/bp-lda#4]
Hello, I'm having problem in trying to execute your code

As per your instruction on README, I did execute the exe through this command
```
"BP_sLDA/bin/Release/BP_sLDA.exe" --nHid 5 --nHidLayer 10 --nInput 5000 --nOutput 1 
                                  --OutputType linearQuad --alpha 1.001 --nEpoch 50 
                                  --BatchSize 1000 --mu_Phi 0.01 --nSamplesPerDisplay 10000 
                                  --TrainLabelFile train.label --TestLabelFile test.label 
                                  --TrainInputFile train.feature --TestInputFile test.feature 
                                  --ResultFile result_Voc5000 --ThreadNum 32 --MaxThreadDeg 32
```
But I received this error, saying that there's a file missing

```
Scanning the file: train.feature

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\Iqbal\Documents\GitHub\bp-lda\train.feature'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at BP_LDA.DataLoader.InputDataLoader(String InputDataFile, Int32 nInput)
   at BP_sLDA.Program.Main(String[] args)
```

How do I fix this problem?

**Comment by jvking** [comment]
For argument "--TrainInputFile train.feature" please change it to your
input feature file location. E.g.
data_AmazonMovieReview_1percent/train.feature

You will need to edit other file path accordingly.

**Comment by miqbal23** [comment]
Thank you for the help. It worked for now

And also a bit of recommendation, you should add information a bit about the platform you used for running the program. This code took quite a lot of resources in my PC so I had to run it on my virtual machine
